# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
STORM_VERSION = "apache-storm-0.9.2-incubating"
STORM_ARCHIVE = "#{STORM_VERSION}.zip"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.hostmanager.manage_host = true
  config.hostmanager.enabled = true
  
  if(!File.exist?(STORM_ARCHIVE))
    `wget -N http://mirror.ox.ac.uk/sites/rsync.apache.org/incubator/storm/apache-storm-0.9.2-incubating/apache-storm-0.9.2-incubating.zip`
  end

    config.vm.define "util" do |util|
      util.vm.box = "precise64"
      util.vm.network "private_network", ip: "192.168.50.7"
      util.vm.hostname = "util"
      util.vm.provision "shell", path: "install-kafka.sh"
      
      util.vm.network "forwarded_port", guest: 12000, host: 12000
      util.vm.network "forwarded_port", guest: 9092, host: 9092
    end


  config.vm.define "zookeeper" do |zookeeper|
    zookeeper.vm.box = "precise64"
    zookeeper.vm.network "private_network", ip: "192.168.50.3"
    zookeeper.vm.hostname = "zookeeper"
    zookeeper.vm.provision "shell", path: "install-zookeeper.sh"

    zookeeper.vm.network "forwarded_port", guest: 2181, host: 2181
  end


  config.vm.define "nimbus" do |nimbus|
    nimbus.vm.box = "precise64"
    nimbus.vm.network "private_network", ip: "192.168.50.4"
    nimbus.vm.hostname = "nimbus"
    
    nimbus.vm.provision "shell", path: "install-storm.sh", args: STORM_VERSION
    
    nimbus.vm.provision "shell", path: "config-supervisord.sh", args: "nimbus"
    
    nimbus.vm.provision "shell", path: "config-supervisord.sh", args: "ui"
    
    nimbus.vm.provision "shell", path: "config-supervisord.sh", args: "drpc"

    nimbus.vm.provision "shell", path: "config-supervisord.sh", args: "logviewer"

    nimbus.vm.provision "shell", path: "start-supervisord.sh"
 
    # Ui   
    nimbus.vm.network "forwarded_port", guest: 8080, host: 8080
    nimbus.vm.network "forwarded_port", guest: 8000, host: 8000
    
    # DRPC
    nimbus.vm.network "forwarded_port", guest: 3772, host: 3772
    nimbus.vm.network "forwarded_port", guest: 3773, host: 3773
    
    # Nimbus
    nimbus.vm.network "forwarded_port", guest: 6627, host: 6627

  end

  config.vm.define "supervisor1" do |supervisor|
    supervisor.vm.box = "precise64"
    supervisor.vm.network "private_network", ip: "192.168.50.5"
    supervisor.vm.hostname = "supervisor1"
    
    supervisor.vm.provision "shell", path: "install-storm.sh", args: STORM_VERSION
    
    supervisor.vm.provision "shell", path: "config-supervisord.sh", args: "supervisor"
    
    supervisor.vm.provision "shell", path: "config-supervisord.sh", args: "logviewer"
    
    supervisor.vm.provision "shell", path: "start-supervisord.sh"
    
  end
  
  config.vm.define "supervisor2" do |supervisor|
    supervisor.vm.box = "precise64"
    supervisor.vm.network "private_network", ip: "192.168.50.6"
    supervisor.vm.hostname = "supervisor2"
    
    supervisor.vm.provision "shell", path: "install-storm.sh", args: STORM_VERSION
    
    supervisor.vm.provision "shell", path: "config-supervisord.sh", args: "supervisor"
    
    supervisor.vm.provision "shell", path: "config-supervisord.sh", args: "logviewer"
    
    supervisor.vm.provision "shell", path: "start-supervisord.sh"
    
  end
  

  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
     vb.gui = false
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
   end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file precise32.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "site.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
